# Netlify deployment configuration
[build]
  # No build command needed for static site
  publish = "."
  
[[headers]]
  # Apply security headers to all paths
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; connect-src 'self'"

[[redirects]]
  # Handle SPA routing (if needed in future)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "user"]}
  headers = {X-Country = ["us"]}

# Environment variables for production
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
